spring:
  web:
    resources:
      static-locations: file:/home/control/IUST/CONTROL/UI/dist/

  path:
    formsFolderPath: /home/control/control-group-site/forms/
    newsFolderPath: /home/control/control-group-site/news/
    scienceCommitteeFolderPath: /home/control/control-group-site/science-committee/

  application:
    name: Control

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8084

data-store:
  dir: "DataStore"
  public:
    dir: "DataStore/public"
    faculties:
      dir: "DataStore/public/faculties"
      images:
        dir: "DataStore/public/faculties/images"
